# Generated by Django 4.2.5 on 2023-09-16 17:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studentsweb', '0004_rename_message_messages_rename_room_rooms_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messages',
            new_name='Message',
        ),
        migrations.RenameModel(
            old_name='Rooms',
            new_name='Room',
        ),
        migrations.RenameModel(
            old_name='Topics',
            new_name='Topic',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='rooms',
            new_name='room',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='topics',
            new_name='topic',
        ),
    ]
