# Generated by Django 4.2.5 on 2023-09-16 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsweb', '0002_topic_room_host_message_room_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
