# Generated by Django 4.2.5 on 2023-09-16 17:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studentsweb', '0003_alter_topic_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='Messages',
        ),
        migrations.RenameModel(
            old_name='Room',
            new_name='Rooms',
        ),
        migrations.RenameModel(
            old_name='Topic',
            new_name='Topics',
        ),
        migrations.RenameField(
            model_name='messages',
            old_name='room',
            new_name='rooms',
        ),
        migrations.RenameField(
            model_name='rooms',
            old_name='topic',
            new_name='topics',
        ),
    ]
